USE [master]
GO

/****** Object:  Database [TRADEProd]    Script Date: 22/5/2023 20:28:18 ******/
CREATE DATABASE [TRADEProd_stg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PlantAndHealth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\tradeprod_stg.mdf' , SIZE = 11264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PlantAndHealth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\tradeprod_stg.ldf' , SIZE = 7616KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TRADEProd].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TRADEProd] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TRADEProd] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TRADEProd] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TRADEProd] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TRADEProd] SET ARITHABORT OFF 
GO

ALTER DATABASE [TRADEProd] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TRADEProd] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TRADEProd] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TRADEProd] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TRADEProd] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TRADEProd] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TRADEProd] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TRADEProd] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TRADEProd] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TRADEProd] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TRADEProd] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TRADEProd] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TRADEProd] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TRADEProd] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TRADEProd] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TRADEProd] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TRADEProd] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TRADEProd] SET RECOVERY FULL 
GO

ALTER DATABASE [TRADEProd] SET  MULTI_USER 
GO

ALTER DATABASE [TRADEProd] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TRADEProd] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TRADEProd] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TRADEProd] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TRADEProd] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TRADEProd] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TRADEProd] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TRADEProd] SET  READ_WRITE 
GO


